### ISSUE TITLE
Mystery Data

### ISSUE THREAD

**Issue by red4stone** [Alexbay218/frc-mscout-client-2019#1]
Hey! My teammate and I were just using your fantastic program, and when we finally figured out how to stick it into a google sheet we found that there were a lot of letter:number pairs which we had no idea how to read or translate. If you could post some sort of key to reading it, that would be amazing :)

![image](https://user-images.githubusercontent.com/33238651/51007740-af898580-1516-11e9-9adf-ee5e68834e27.png)

**Comment by Alexbay218** [comment]
Hi, thanks for the interest and sorry for the unpolished state that its in. The key is that after the "hatchCount,0;:" portion, the rest of the data is in event-based key pairs (example "a,0.05;b,1.56"). Split the data by the ";" (it looks like you did this from the image) and each key pair is in "[event key letter],[timestamp in seconds from start of game]" format. 
Use https://github.com/Alexbay218/frc-mscout-client-2019/blob/master/config/eventConfig.js to digest the data. For example, "g,3.685" is "Scored on Cargo Ship" at 3.685 seconds from the start of the game. Google sheets is honestly not meant for processing this, and I'm working on developing an analytics app to really utilize the power of event-based match data.
You can contact me on discord at user: Alexbay218#0295
Thanks for your interest!!

**Comment by Alexbay218** [comment]
https://github.com/Alexbay218/frc-mscout-analytics-2019
The analytics app is up and you can export the data if you want.
